- name: Add Grafana repository
  yum_repository:
    name: "{{ centos.grafana_repo_name }}"
    description: "{{ centos.grafana_repo_description }}"
    baseurl: "{{ centos.grafana_repo_url }}"
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "{{ centos.grafana_repo_key_url }}"
  tags:
    - grafana

- name: Install grafana
  package:
    name: grafana
    state: present
  notify:
    - init grafana service
  tags:
    - grafana

- name: install grafana clock plugins
  command: grafana-cli plugins install "{{ item }}"
  loop:
    - grafana-clock-panel
    - grafana-piechart-panel
  notify:
    - restart grafana service
  tags:
    - grafana

- name: configure grafana
  template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify:
    - restart grafana service
  tags:
    - run    



