centos:
  grafana_repo_url: https://packages.grafana.com/oss/rpm
  grafana_repo_key_url:  https://packages.grafana.com/gpg.key
  grafana_repo_name: grafana
  grafana_repo_description: grafana YUM repository
  grafana_init_file: /etc/sysconfig/grafana-server
