- name: Install firewalld
  package:
    name: firewalld
    state: present

- name: Enable firewalld
  service: 
    name: firewalld
    state: started
    enabled: yes

- name: Allow grafana port 
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  notify: 
    - restart firewalld service    

- name: set selinux to allow nginx to grafana conn
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes






